spring.application.name=aura
spring.datasource.url=jdbc:mysql://localhost:3306/aura
spring.datasource.username=root
spring.datasource.password=Anika@Tomar999
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000  # in milliseconds
spring.datasource.hikari.max-lifetime=1800000  # in milliseconds